liip_imagine:
    driver: "gd"
    filter_sets:
        34x34:
            jpeg_quality: 85
            filters:
                thumbnail: { size: [34, 34], mode: outbound, allow_upscale: true }
        64x64:
            jpeg_quality: 85
            filters:
                thumbnail: { size: [64, 64], mode: outbound, allow_upscale: true }
        120x120:
            jpeg_quality: 85
            filters:
                thumbnail: { size: [120, 120], mode: outbound, allow_upscale: true }
        200x200:
            jpeg_quality: 85
            filters:
                thumbnail: { size: [200, 200], mode: outbound, allow_upscale: true }
        240x240:
            jpeg_quality: 85
            filters:
                thumbnail: { size: [240, 240], mode: outbound, allow_upscale: true }
        300x300:
            jpeg_quality: 85
            filters:
                thumbnail: { size: [300, 300], mode: outbound, allow_upscale: true }