back_index:
   path: /admin
   controller: App\Controller\BackController::index

back_pros:
   path: /admin/pros
   controller: App\Controller\BackController::pros

back_pros_add:
   path: /admin/pros/add
   controller: App\Controller\BackController::prosAdd

back_pros_edit:
   path: /admin/pros/{id}/edit
   controller: App\Controller\BackController::prosEdit

back_parts:
   path: /admin/parts
   controller: App\Controller\BackController::parts

back_parts_add:
   path: /admin/parts/add
   controller: App\Controller\BackController::partsAdd

back_parts_edit:
   path: /admin/parts/{id}/edit
   controller: App\Controller\BackController::partsEdit

back_users:
   path: /admin/users
   controller: App\Controller\BackController::users

back_users_add:
   path: /admin/users/add
   controller: App\Controller\BackController::usersAdd

back_users_edit:
   path: /admin/users/{id}/edit
   controller: App\Controller\BackController::usersEdit

back_cities:
   path: /admin/cities
   controller: App\Controller\BackController::cities

back_cities_add:
   path: /admin/cities/add
   controller: App\Controller\BackController::citiesAdd

back_cities_edit:
   path: /admin/cities/{id}/edit
   controller: App\Controller\BackController::citiesEdit

back_cars:
   path: /admin/cars
   controller: App\Controller\BackController::cars

back_cars_add:
   path: /admin/cars/add
   controller: App\Controller\BackController::carsAdd

back_cars_edit:
   path: /admin/cars/{id}/edit
   controller: App\Controller\BackController::carsEdit

back_trademarks:
   path: /admin/trademarks
   controller: App\Controller\BackController::trademarks

back_trademarks_add:
   path: /admin/trademarks/add
   controller: App\Controller\BackController::trademarksAdd

back_trademarks_edit:
   path: /admin/trademarks/{id}/edit
   controller: App\Controller\BackController::trademarksEdit

back_models:
   path: /admin/models
   controller: App\Controller\BackController::models

back_models_add:
   path: /admin/models/add
   controller: App\Controller\BackController::modelsAdd

back_models_edit:
   path: /admin/models/{id}/edit
   controller: App\Controller\BackController::modelsEdit

back_versions:
   path: /admin/versions
   controller: App\Controller\BackController::versions

back_versions_add:
   path: /admin/versions/add
   controller: App\Controller\BackController::versionsAdd

back_versions_edit:
   path: /admin/versions/{id}/edit
   controller: App\Controller\BackController::versionsEdit

back_posts:
   path: /admin/posts
   controller: App\Controller\BackController::posts

back_posts_add:
   path: /admin/posts/add
   controller: App\Controller\BackController::postsAdd

back_posts_edit:
   path: /admin/posts/{id}/edit
   controller: App\Controller\BackController::postsEdit

back_demands:
   path: /admin/demands
   controller: App\Controller\BackController::demands

back_demands_add:
   path: /admin/demands/add
   controller: App\Controller\BackController::demandsAdd

back_demands_edit:
   path: /admin/demands/{id}/edit
   controller: App\Controller\BackController::demandsEdit

back_offers:
   path: /admin/offers
   controller: App\Controller\BackController::offers

back_offers_add:
   path: /admin/offers/add
   controller: App\Controller\BackController::offersAdd

back_offers_edit:
   path: /admin/offers/{id}/edit
   controller: App\Controller\BackController::offersEdit

back_conversations:
   path: /admin/conversations
   controller: App\Controller\BackController::conversations

back_conversations_edit:
   path: /admin/conversations/{id}/edit
   controller: App\Controller\BackController::conversationsEdit

back_messages:
   path: /admin/messages
   controller: App\Controller\BackController::messages

back_messages_edit:
   path: /admin/messages/{id}/edit
   controller: App\Controller\BackController::messagesEdit

back_responses:
   path: /admin/responses
   controller: App\Controller\BackController::responses

back_responses_edit:
   path: /admin/responses/{id}/edit
   controller: App\Controller\BackController::responsesEdit

back_plans:
   path: /admin/plans
   controller: App\Controller\BackController::plans

back_plans_add:
   path: /admin/plans/add
   controller: App\Controller\BackController::plansAdd

back_plans_edit:
   path: /admin/plans/{id}/edit
   controller: App\Controller\BackController::plansEdit

back_subscriptions:
   path: /admin/subscriptions
   controller: App\Controller\BackController::subscriptions

back_subscriptions_add:
   path: /admin/subscriptions/add
   controller: App\Controller\BackController::subscriptionsAdd

back_subscriptions_edit:
   path: /admin/subscriptions/{id}/edit
   controller: App\Controller\BackController::subscriptionsEdit

back_historics:
   path: /admin/historics
   controller: App\Controller\BackController::historics

back_historics_add:
   path: /admin/historics/add
   controller: App\Controller\BackController::historicsAdd

back_historics_edit:
   path: /admin/historics/{id}/edit
   controller: App\Controller\BackController::historicsEdit

back_faqs:
   path: /admin/faqs
   controller: App\Controller\BackController::faqs

back_faqs_add:
   path: /admin/faqs/add
   controller: App\Controller\BackController::faqsAdd

back_faqs_edit:
   path: /admin/faqs/{id}/edit
   controller: App\Controller\BackController::faqsEdit

blog:
   path: /blog

registration_register:
   path: /inscription.html
   controller: App\Controller\RegistrationController::register

security_login:
   path: /connexion.html
   controller: App\Controller\SecurityController::login

security_confirm:
   path: /confirm/{id}/{token<[a-zA-Z0-9]{60}>}
   controller: App\Controller\RegistrationController::confirm

security_logout:
   path: /deconnexion.html
   controller: App\Controller\SecurityController::logout

test_demand:
   path: /test-demande.html
   controller: App\Controller\HomeController::test_demand

page:
   path: /{slug<[a-z0-9-]+(\.html)>?}
   controller: App\Controller\HomeController::page

accounts:
   path: /moncompte/{slug<[a-z0-9-]+(\.html)>?}
   controller: App\Controller\HomeController::page
